name: foundation
description: Foundation stack which includes setup and provisioning of the OS / k8s. This is the first layer of the homelab infrastructure.
author: Yevhenii Vasylenko
website: https://github.com/tech-paladin/homelab
license: MIT
requiredPulumiVersion: ">= 3.250.0"
runtime: go
config:
  pulumi:tags:
    value:
      pulumi:template: go
